[package]
name = "l10nregistry"
version = "0.1.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["fs", "rt-threaded", "macros"] }
unic-langid = "0.9"
itertools = "0.9"
