[package]
name = "l10nregistry"
version = "0.1.1"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
async-trait = "0.1"
chunky-vec = "0.1"
fluent-bundle = { version = "0.13", path = "../fluent-rs/fluent-bundle" }
fluent-fallback = { path = "../fluent-rs/fluent-fallback" }
futures = "0.3"
itertools = "0.9"
log = "0.4"
pin-project = "1.0"
unic-langid = "0.9"
tokio = { version = "0.3", optional = true, features = ["fs", "rt-multi-thread", "macros", "io-util"] }

[dev-dependencies]
unic-langid = { version = "0.9", features = ["macros"] }
serial_test = "0.5"

[features]
default = []
tokio-io = ["tokio"]

[[test]]
name = "source"
path = "tests/source.rs"
required-features = ["tokio"]

[[test]]
name = "registry"
path = "tests/registry.rs"
required-features = ["tokio"]

[[test]]
name = "localization"
path = "tests/localization.rs"
required-features = ["tokio"]
